dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  fast_finish: true

  include:
    # Meta
    - python: "3.7"
      env: NOXSESSION="lint"
    - python: "3.7"
      env: NOXSESSION="doc"

    # Test
    - python: "3.6"
      env: NOXSESSION="test-3.6"
    - python: "3.7"
      env: NOXSESSION="test-3.7"

    # Prevent breakage on new releases
    - python: "3.7-dev"
      env: NOXSESSION="test-3.7"
    - python: "3.8-dev"
      env: NOXSESSION="test-3.8"

allow_failures:
  - python: "3.7-dev"
  - python: "3.8-dev"

install:
  - pip install -U nox

script:
  - nox --non-interactive --session "$NOXSESSION"

notifications:
  email: false
